### ISSUE TITLE
fbclid fix

### ISSUE THREAD

**Issue by anonine9899** [nboughton/nofbclid#1]
I clicked on a link on FB messenger: https://addons.mozilla.org/en-US/firefox/addon/nofbclid/?src=search
I saw that the fbclid param is still in the url row right after an a '&' mark:
'https://addons.mozilla.org/en-US/firefox/addon/nofbclid/?src=search&fbclid=IwAR0..........'

**Comment by nboughton** [comment]
I'm afraid I'm insanely busy at the moment. I had a quick look at this but can only replicate it on addons.mozilla.org. The extension seems to work fine for every other site I tried. My best guess would be that Firefox disables URI manipulation on the extension site as a security measure but I don't really have time to look into it any further just right now.

I'll leave this issue open for now and hopefully have some time to look into it further in a week or two.

**Comment by hippi777** [comment]
hi there! :)

this can be closed.

the page, https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension says this:
"Don't try it on addons.mozilla.org, though! Content scripts are currently blocked on that domain."

all the bests to both of you! :)
